version: "3.8"

services:

  db:
    extends:
      file: docker-compose-1.yml
      service: db

  tki:
    extends:
      file: docker-compose-1.yml
      service: tki

  app:
    image: my_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000-8010:8000"

name: workshop


